# Generated by Django 2.2 on 2019-04-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('PublishTime', models.DateTimeField(default=0)),
                ('location', models.CharField(max_length=15)),
                ('blog', models.TextField(default='')),
            ],
        ),
    ]
