# Generated by Django 2.2 on 2019-04-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='PublishTime',
            new_name='publishtime',
        ),
    ]
